services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=ttracker-db
      - POSTGRES_USER=ttracker-user
      - POSTGRES_PASSWORD=ttracker-password
    ports:
      - '5432:5432'
    volumes:
      - ../ttracker-db:/var/lib/postgresql/data
