# Sat Dec 13 04:32:40 UTC 2025
micronaut:
  application:
    name: ttrack-be
  router:
    static-resources:
      swagger:
        paths: "classpath:META-INF/swagger"
        mapping: "/swagger/**"
      swagger-ui:
        mapping: "/swagger-ui/**"
        paths: "classpath:META-INF/swagger/views/swagger-ui"
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "PlsChangeThis!!PlsChangeThis!!PlsChangeThis!!PlsChangeThis!!"
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /auth
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /user/create
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/ttrack-db
    driverClassName: org.postgresql.Driver
    username: ttrack-user
    password: ttrack-password
    dialect: POSTGRES
    autoCommit: false
    connectionTimeout: 30000
    minimumIdle: 5
    maximumPoolSize: 10

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

jpa:
  default:
    entity-scan:
      packages: 'com.rvladimir.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        format_sql: true
