# Sat Dec 13 04:32:40 UTC 2025
micronaut:
  application:
    name: ttrack-be
  router:
    static-resources:
      swagger:
        paths: "classpath:META-INF/swagger"
        mapping: "/swagger/**"
      swagger-ui:
        mapping: "/swagger-ui/**"
        paths: "classpath:META-INF/swagger/views/swagger-ui"
